In [9]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

from sklearn.datasets import make_blobs
%matplotlib widget
from matplotlib.widgets import Slider

import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

In [8]:
!pip install ipympl


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.6/511.6 kB 280.2 kB/s eta 0:00:00a 0:00:01


In [10]:
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

In [11]:
model = Sequential(
    [ 
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'softmax')    # < softmax activation here
    ]
)
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.001),
)

model.fit(
    X_train,y_train,
    epochs=10
)

Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB

Epoch 1/10
63/63 [==============================] - 7s 29ms/step - loss: 1.2395
Epoch 2/10
63/63 [==============================] - 0s 8ms/step - loss: 0.4793
Epoch 3/10
63/63 [==============================] - 1s 9ms/step - loss: 0.2124
Epoch 4/10
63/63 [==============================] - 1s 8ms/step - loss: 0.1166
Epoch 5/10
63/63 [==============================] - 1s 9ms/step - loss: 0.0765
Epoch 6/10
63/63 [==============================] - 0s 8ms/step - loss: 0.0609
Epoch 7/10
63/63 [==============================] - 0s 8ms/step - loss: 0.0521
Epoch 8/10
63/63 [==============================] - 0s 8ms/step - loss: 0.0462
Epoch 9/10
63/63 [==============================] - 0s 7ms/step - loss: 0.0416
Epoch 10/10
63/63 [==============================] - 1s 8ms/step - loss: 0.0382


In [12]:
p_nonpreferred = model.predict(X_train)
print(p_nonpreferred [:2])
print("largest value", np.max(p_nonpreferred), "smallest value", np.min(p_nonpreferred))

63/63 [==============================] - 1s 8ms/step
[[2.2130159e-03 5.5222400e-03 9.8189974e-01 1.0365018e-02]
 [9.9142742e-01 8.4874080e-03 8.5081454e-05 9.0676039e-08]]
largest value 0.99999857 smallest value 4.5952513e-12


In [13]:
preferred_model = Sequential(
    [ 
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'linear')   #<-- Note
    ]
)
preferred_model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),  #<-- Note
    optimizer=tf.keras.optimizers.Adam(0.001),
)

preferred_model.fit(
    X_train,y_train,
    epochs=10
)
       

Epoch 1/10
63/63 [==============================] - 3s 23ms/step - loss: 0.7918
Epoch 2/10
63/63 [==============================] - 0s 8ms/step - loss: 0.2655
Epoch 3/10
63/63 [==============================] - 1s 9ms/step - loss: 0.1351
Epoch 4/10
63/63 [==============================] - 1s 8ms/step - loss: 0.0912
Epoch 5/10
63/63 [==============================] - 1s 8ms/step - loss: 0.0714
Epoch 6/10
63/63 [==============================] - 1s 8ms/step - loss: 0.0606
Epoch 7/10
63/63 [==============================] - 0s 8ms/step - loss: 0.0540
Epoch 8/10
63/63 [==============================] - 0s 8ms/step - loss: 0.0485
Epoch 9/10
63/63 [==============================] - 0s 8ms/step - loss: 0.0444
Epoch 10/10
63/63 [==============================] - 0s 8ms/step - loss: 0.0410


In [14]:
p_preferred = preferred_model.predict(X_train)
print(f"two example output vectors:\n {p_preferred[:2]}")
print("largest value", np.max(p_preferred), "smallest value", np.min(p_preferred))

63/63 [==============================] - 1s 7ms/step
two example output vectors:
 [[-3.832939   -3.338976    2.7534573  -0.5013954 ]
 [ 4.6883416  -0.37896216 -4.463575   -8.111472  ]]
largest value 11.2758875 smallest value -11.505201


In [15]:
sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f"two example output vectors:\n {sm_preferred[:2]}")
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

two example output vectors:
 [[1.3231308e-03 2.1683448e-03 9.5948541e-01 3.7023179e-02]
 [9.9363273e-01 6.2592714e-03 1.0534139e-04 2.7437034e-06]]
largest value 1.0 smallest value 2.5269729e-09


In [16]:
for i in range(5):
    print( f"{p_preferred[i]}, category: {np.argmax(p_preferred[i])}")

[-3.832939  -3.338976   2.7534573 -0.5013954], category: 2
[ 4.6883416  -0.37896216 -4.463575   -8.111472  ], category: 0
[ 3.3673778   0.12430378 -3.5789936  -6.422926  ], category: 0
[-2.2490363  4.181399  -3.1093087 -2.4159923], category: 1
[-2.697525  -4.483143   3.6414475 -2.8406577], category: 2
